### ISSUE TITLE
Attach a finished drawing event to the Flotr

### ISSUE THREAD

**Issue by amirmog** [HumbleSoftware/Flotr2#315]
I have been searching everywhere to just understand how to add a callback or an event handler which gets triggered when the Flotr graph is actually finished with its drawing.

My graph draws okay with small or mid size data but when I use a larger set of data, the graph takes much longer to draw. While it's trying to draw, the graph container is blank so I would like to show a loading spinner while it's trying to draw and hide this spinner when the graph is actually finished with its drawing.

So my question is how to know when the graph has really completed its drawing?
 
Could someone please point me to the right direction or provide with some code sample.
Any help would be much much appreciated.

Thank you,

**Comment by amirmog** [comment]
Any help...? Thanks

**Comment by cesutherland** [comment]
Hey Amir,

Drawing happens synchronously!  So you can execute your "after" code right
after calling the Flotr draw method.

-c

**Comment by amirmog** [comment]
Hey Carl,

Okay awesome, I just realized that as I sandwiched the drawing code in between 'befoer' nad 'after' code.
Thanks for your help,
Cheers.

**Comment by cesutherland** [comment]
Cheers!
